name: Continuous Deployment
on: 
  push:
    branches:
      - master
jobs:
  markdown_lint:
    name: Run Markdown Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Markdown Lint
        uses: ./.github/actions/lint-markdown
  convert_pandoc:
    name: Convert Files using Pandoc
    needs: markdown_lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Convert Markdown to DOCX
        uses: ./.github/actions/pandoc-convert
      - name: Archive document artifacts
        uses: actions/upload-artifact@v1
        with:
          name: documents
          path: /app/pkg/