name: Continuous Integration
on: push
jobs:
  convert_pandoc:
    name: Convert Files using Pandoc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/pandoc-convert