name: Continuous Integration
on: push
jobs:
  markdown_lint:
    name: Run Markdown Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/lint-markdown