name: Continuous Integration
on: pull_request
jobs:
  markdown_lint:
    name: Run Markdown Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Markdown Lint
        uses: ./.github/actions/lint-markdown